%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/kilted/.*$
%global __requires_exclude_from ^/opt/ros/kilted/.*$

Name:           ros-kilted-rmf-visualization-building-systems
Version:        2.4.1
Release:        2%{?dist}%{?release_suffix}
Summary:        ROS rmf_visualization_building_systems package

License:        Apache License 2.0
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kilted-geometry-msgs
Requires:       ros-kilted-rmf-building-map-msgs
Requires:       ros-kilted-rmf-door-msgs
Requires:       ros-kilted-rmf-lift-msgs
Requires:       ros-kilted-rmf-visualization-msgs
Requires:       ros-kilted-ros-workspace
BuildRequires:  python%{python3_pkgversion}-devel
BuildRequires:  ros-kilted-geometry-msgs
BuildRequires:  ros-kilted-rmf-building-map-msgs
BuildRequires:  ros-kilted-rmf-door-msgs
BuildRequires:  ros-kilted-rmf-lift-msgs
BuildRequires:  ros-kilted-rmf-visualization-msgs
BuildRequires:  ros-kilted-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  python%{python3_pkgversion}-pytest
BuildRequires:  ros-kilted-ament-copyright
BuildRequires:  ros-kilted-ament-flake8
BuildRequires:  ros-kilted-ament-pep257
%endif

%description
A visualizer for doors and lifts

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%py3_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%py3_install -- --prefix "/opt/ros/kilted"

%if 0%{?with_tests}
%check
# Look for a directory with a name indicating that it contains tests
TEST_TARGET=$(ls -d * | grep -m1 "\(test\|tests\)" ||:)
if [ -n "$TEST_TARGET" ] && %__python3 -m pytest --version; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%__python3 -m pytest $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/kilted

%changelog
* Tue Apr 22 2025 Yadunund <yadunund@openrobotics.org> - 2.4.1-2
- Autogenerated by Bloom

* Wed Nov 27 2024 Yadunund <yadunund@openrobotics.org> - 2.4.1-1
- Autogenerated by Bloom

* Sat Jun 15 2024 Yadunund <yadunund@openrobotics.org> - 2.4.0-1
- Autogenerated by Bloom

* Thu Jun 06 2024 Yadunund <yadunund@openrobotics.org> - 2.3.1-1
- Autogenerated by Bloom

* Mon Jun 03 2024 Yadunund <yadunund@openrobotics.org> - 2.3.0-1
- Autogenerated by Bloom

* Wed Mar 06 2024 Yadunund <yadunund@openrobotics.org> - 2.2.1-2
- Autogenerated by Bloom

