%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/humble/.*$
%global __requires_exclude_from ^/opt/ros/humble/.*$

Name:           ros-humble-rmf-visualization-rviz2-plugins
Version:        2.0.0
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS rmf_visualization_rviz2_plugins package

License:        Apache License 2.0
Source0:        %{name}-%{version}.tar.gz

Requires:       qt5-qtbase
Requires:       qt5-qtbase-gui
Requires:       ros-humble-pluginlib
Requires:       ros-humble-rclcpp
Requires:       ros-humble-resource-retriever
Requires:       ros-humble-rmf-door-msgs
Requires:       ros-humble-rmf-lift-msgs
Requires:       ros-humble-rmf-traffic-ros2
Requires:       ros-humble-rmf-visualization-msgs
Requires:       ros-humble-rviz-common
Requires:       ros-humble-rviz-default-plugins
Requires:       ros-humble-rviz-rendering
Requires:       ros-humble-ros-workspace
BuildRequires:  eigen3-devel
BuildRequires:  qt5-qtbase-devel
BuildRequires:  ros-humble-ament-cmake
BuildRequires:  ros-humble-pluginlib
BuildRequires:  ros-humble-rclcpp
BuildRequires:  ros-humble-resource-retriever
BuildRequires:  ros-humble-rmf-door-msgs
BuildRequires:  ros-humble-rmf-lift-msgs
BuildRequires:  ros-humble-rmf-traffic-ros2
BuildRequires:  ros-humble-rmf-visualization-msgs
BuildRequires:  ros-humble-rviz-common
BuildRequires:  ros-humble-rviz-default-plugins
BuildRequires:  ros-humble-rviz-rendering
BuildRequires:  ros-humble-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  ros-humble-ament-cmake-uncrustify
BuildRequires:  ros-humble-rmf-utils
%endif

%description
A package containing RViz2 plugins for RMF

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/humble/setup.sh" ]; then . "/opt/ros/humble/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/humble" \
    -DAMENT_PREFIX_PATH="/opt/ros/humble" \
    -DCMAKE_PREFIX_PATH="/opt/ros/humble" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/humble/setup.sh" ]; then . "/opt/ros/humble/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/humble/setup.sh" ]; then . "/opt/ros/humble/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/humble

%changelog
* Mon Oct 03 2022 Yadunund <yadunund@openrobotics.org> - 2.0.0-1
- Autogenerated by Bloom

* Tue Apr 19 2022 Yadunund <yadunund@openrobotics.org> - 1.2.1-3
- Autogenerated by Bloom

* Tue Feb 08 2022 Yadunund <yadunund@openrobotics.org> - 1.2.1-2
- Autogenerated by Bloom

